"use strict";

const SESSION_COLLECTION = "sessions";
const SESSION_TTL_MS = 12 * 60 * 60 * 1000;
const SESSION_TOUCH_INTERVAL_MS = 5 * 60 * 1000;
const LOGIN_ATTEMPT_COLLECTION = "loginAttempts";
const LOGIN_FAIL_LIMIT = 5;
const LOGIN_BLOCK_MS = 5 * 60 * 1000;

module.exports = {
  SESSION_COLLECTION,
  SESSION_TTL_MS,
  SESSION_TOUCH_INTERVAL_MS,
  LOGIN_ATTEMPT_COLLECTION,
  LOGIN_FAIL_LIMIT,
  LOGIN_BLOCK_MS
};
